name = "webfinger"
main = "webfinger.js"

workers_dev = false
route = { pattern = "https://marckohlbrugge.com/.well-known/webfinger*", zone_name = "marckohlbrugge.com" }
compatibility_date = "2023-02-10"
